name: Build & Attach latest.zip

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore MoonMagic/MoonMagic.csproj

      - name: Build (Release x64)
        run: dotnet build MoonMagic/MoonMagic.csproj -c Release -p:Platform=x64

      - name: Verify dist zip exists
        shell: pwsh
        run: |
          if (!(Test-Path "MoonMagic\bin\Release\dist\latest.zip")) {
            throw "dist/latest.zip not found. Check Manifest.json and DalamudPackager settings."
          }

      - name: Attach latest.zip to Release
        uses: softprops/action-gh-release@v2
        with:
          files: MoonMagic/bin/Release/dist/latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
